name: Send Message to Telegram

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Send Message to Telegram
        run: |
          echo "Sending message to Telegram..."
          response=$(curl -s -w "%{http_code}" -X GET "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.CHAT_ID }}&text=${{ github.event.inputs.message }}")
          http_code=$(echo "$response" | tail -n 1)
          if [ "$http_code" -ne 200 ]; then
            echo "Error sending message. HTTP Status Code: $http_code"
            exit 1
          fi
          echo "Message sent successfully!"
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
