name: Send Telegram Message

on:
  repository_dispatch:
    types: [send-telegram-message]

jobs:
  send-telegram-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Send Telegram Message
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
          -d chat_id=${{ secrets.CHAT_ID }} \
          -d text="New Claim Submitted:\nName: ${{ github.event.client_payload.name }}\nSex: ${{ github.event.client_payload.sex }}\nAge: ${{ github.event.client_payload.age }}\nEmail: ${{ github.event.client_payload.email }}\nMessage: ${{ github.event.client_payload.message }}"
